pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
        // TODO: run this simple pipeline on jenkins 'master' node
        label 'master'
      }
    }

    stages {

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }
        stage('stage 2') {
          steps { 
            sh 'echo Hello, World!'
	  }
        }
	stage('manual approval') {
	  steps {
       	    // TODO: ADD AN APPROVAL STAGE
            timeout(time: 60, unit: 'MINUTES') {
              input message: 'Continue?'
              }
            }
          }
        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
